### PR TITLE
Adding Support for SwaggerHub Domains

### PR DESCRIPTION
**Pull request by aeneal**
SwaggerHub Has domains it makes sense to support the domains resource as well as the apis one.

### CODE REVIEW

**Comment by michaelmelodysmartbear** [comment]
Looks good to me. @jsfrench Any thoughts?

**Comment by jsfrench** [comment]
I'm wondering if it's really necessary to create separate `uploadDomain` and `downloadDomain` tasks for this? Seems like a lot of extra overhead. Maybe this could be achieved more easily with an optional parameter called something like `type` on the existing `upload` and `download` tasks, with potential values of `api` and `domain`, defaulting to `api`?

**Comment by aeneal** [comment]
I would like that it was an optional parameter, but the fact you named the specifictation Name as 'api' made that Flow a little difficult. 

I might re-work it so that api becomes optional, introduce a 'domain' field and throw an error if at least one is not found

**Comment by aeneal** [comment]
Updated Pull request - moves to v2 on the basis of a name change from 'api' to 'specName'

**Comment by aeneal** [comment]
@jsfrench any thoughts on this?

**Comment by aeneal** [comment]
@jsfrench any updates?

**Comment by michaelmelodysmartbear** [comment]
@aeneal - Let me have a look through this PR. I'd like to hold off on this for the time being; reason being that I'd like to see what effort there would be to abstract common functionality between both this plugin and the https://github.com/swagger-api/swaggerhub-maven-plugin. At this time we have Gradle far behind the Maven plugin in terms of what they offer. If we were to accept this PR, we would face a scenario both plugins have moved in separate directions.

@webron  I know we talked about this before, let's pick this up at some stage soon. Like we discussed, we could abstract this functionality into an appropriate location and simply "wrap" both Maven and Gradle support on top of this.

@aeneal Apologies on the delay on responding to this!

**Comment by webron** [comment]
@michaelmelodysmartbear you know how to find me 😉

**Comment by aeneal** [comment]
@michaelmelodysmartbear thanks for your feedback, appreciated. 

In the interim I've written my own plugin to achieve my needs, https://github.com/aeneal/new-swaggerHub-gradle-plugin - principally It allows me to download multiple specifications across many organisations as well as use openApi Resolver to resolve my downloads as opposed to just ok HTTP to get a raw file, which is somewhat more useful for a api first approach. happy to help collaborate and speed this up - we've just gone enterprise but there are a raft of limitations we want to push through without having to keep writing our own stuff

**Comment by michaelmelodysmartbear** [comment]
@aeneal What other limitations are you seeing? We can use them to inform the design for what I mentioned above. It's probably the time to bring the plugins in line and push them along in terms of functionality.

**Comment by aeneal** [comment]
@michaelmelodysmartbear
for this plugin:
- can only retrieve one specification without writing many Gradle tasks, 
- resolving specifications once you have them - the SwaggerHub UX allows this for API's but the API doesn't support it. 
- specifying a directory as opposed to filename on downloads
- as per this pull request supporting domains
- validation on POST
but these are just our needs.

**Comment by michaelmelodysmartbear** [comment]
@aeneal Thanks for that. @webron I've a couple of ideas around this, I'll mail you this evening :)

**Comment by ddcprg** [comment]
any updates on this issue?

**Pull request closed without merging**
